config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :categories do
    resources :tasks do
      collection do
        get 'today'
      end
    end
  end

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  validates :title, presence: true

  scope :today, -> { where("created_at >= ?", Time.zone.now.beginning_of_day) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @tasks = @category.tasks
  end

  def new
    @category = Category.new
  end

  def edit
    # Edit action logic for categories
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
   
    @category.tasks.destroy_all
    redirect_to categories_url, notice: 'Category and associated tasks were successfully deleted.'
  end
  

  private

  def set_category
    @category = Category.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Category not found"
    redirect_to categories_path
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_category
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  

  def index
    @tasks = @category.tasks
  end

  def show
  end

  def new
    @task = @category.tasks.build
  end

  def edit
  end

  def create
    @task = @category.tasks.build(task_params)
    if @task.save
      redirect_to [@category, @task], notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to [@category, @task], notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to category_tasks_path(@category), notice: 'Task was successfully deleted.'
  end

  def today
    @tasks = @category.tasks.where(due_date: Date.today)
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Category not found"
    redirect_to categories_path
  end

  def set_task
    @task = @category.tasks.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Task not found"
    redirect_to category_tasks_path(@category)
  end

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Category' %>
  </div>
<% end %>

<%= link_to 'Cancel', categories_path %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<!-- Heading for the Edit Category page -->

<%= render 'form', category: @category %>
<!-- Renders the _form partial, passing the @category object to it -->

app/views/categories/index.html.erb
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td>
          <%= link_to 'Show Tasks', category_tasks_path(category), class: 'btn btn-primary' %>
          <%= link_to 'Tasks for Today', today_category_tasks_path(category), class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-primary' %>
          <%= button_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_with(model: @category, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p><%= @category.description %></p>

<h2>Tasks</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Due Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @category.tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= link_to 'Show', category_task_path(@category, task) %></td>
        <td><%= link_to 'Edit', edit_category_task_path(@category, task) %></td>
        <td><%= link_to 'Delete', category_task_path(@category, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %> |
<%= link_to 'New Task', new_category_task_path(@category) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Journal</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "custom", media: "all" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <header>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>

  <%= yield %>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: [@category, @task], local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task for <%= @category.name %></h1>

<%= form_with(model: [@category, @task], local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Task' %>
  </div>
<% end %>

<%= link_to 'Back', category_tasks_path(@category) %>

app/views/tasks/index.html.erb
<h1>Tasks for <%= @category.name %></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, category_task_path(@category, task) %></td>
        <td><%= task.description %></td>
        <td>
          <%= link_to 'Edit', edit_category_task_path(@category, task) %>
          <%= link_to 'Delete', category_task_path(@category, task), method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Task', new_category_task_path(@category) %>
<%= link_to 'Back to Categories', categories_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', category_tasks_path(@category) %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.description %></p>

<p><strong>Category:</strong> <%= @task.category.name %></p>

<%= link_to 'Edit', edit_category_task_path(@category, @task) %> |
<%= link_to 'Back', category_tasks_path(@category) %>
<%= button_to 'Delete', category_task_path(@category, @task), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/tasks/today.html.erb
<h1>Tasks for Today</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Due Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td>
          <%= link_to 'Show', [task.category, task], class: 'btn btn-primary' %>
          <%= link_to 'Edit', edit_category_task_path(task.category, task), class: 'btn btn-primary' %>
          <%= link_to 'Delete', category_task_path(task.category, task), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Categories', categories_path, class: 'btn btn-secondary' %>